In [3]:
import torch

def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/size: {}".format(x.shape))
    print("Values: \n{}".format(x))

describe(torch.Tensor(2, 3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1.5929e+20, 1.3563e-19, 8.4828e-33],
        [1.3563e-19, 9.4500e+08, 1.3585e-19]])


In [5]:
describe(torch.rand(2, 3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.1999, 0.8531, 0.7326],
        [0.6572, 0.1187, 0.5357]])


In [6]:
describe(torch.randn(2, 3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.0139,  0.4684,  1.2721],
        [-0.4702,  0.6761,  0.7318]])


In [7]:
describe(torch.zeros(2, 3))
x = torch.ones(2, 3)
describe(x)
x.fill_(5)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [8]:
y = (x + 2) * (x + 5) + 3
describe(y)
print(x.grad is None)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[73., 73., 73.],
        [73., 73., 73.]])
True


In [10]:
import torch
print (torch.cuda.is_available())

True


In [14]:
device = torch.device("cpu")
print (device)

cpu


In [15]:
x = torch.rand(3, 3).to(device)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[0.4915, 0.6540, 0.0942],
        [0.5709, 0.6800, 0.9422],
        [0.7907, 0.8396, 0.9826]])
